site_name: SR NJU
theme:
  name: 'material'
nav:
  - 关于我们: index.md
  - 服务器技术文档:
    - 服务器基本信息: 1/1_1.md
    - 环境信息: 1/1_2.md
  - mkdocs操作文档: 2/2.md
  - Python虚拟环境:
    - 预备知识: 3/3_1.md
    - Windows配置虚拟环境: 3/3_2.md
    - 复现THU-DL-SR记录: 3/3_3.md
