site_name: SR NJU
theme: 
  name: readthedocs
nav:
  - Index: index.md
  - 一、mkdocs & Git: 
    - 1.1 mkdocs 的安装与使用: 1/1_1.md
    - 1.2 Markdown 基础语法: 1/1_2.md
    - 1.3 Git 与 Github 操作: 1/1_3.md
  - 二、服务器技术文档:
    - 2.1 服务器基本信息: 2/2_1.md
    - 2.2 服务器环境信息: 2/2_2.md
    - 2.3 服务器使用方法: 2/2_3.md
    - 2.4 服务器问题与解决: 2/gpu_summary.md
  - 三、Python技术文档:
    - 3.1 虚拟环境预备知识: 3/3_1.md
    - 3.2 Windows配置虚拟环境: 3/3_2.md
    - 3.3 复现THU-DL-SR记录(暂停维护): 3/3_3.md
    - 3.4 python问题与解决: 3/py_summary.md
  - 四、程序技术文档:
    - 4.1 程序总架构: 4/4_1.md
    - 4.2 根目录: 4/4_2.md
    - 4.3 datasets模块: 4/4_3.md
    - 4.4 functions模块: 4/4_4.md
    - 4.5 manual_saves模块: 4/4_5.md
    - 4.6 modules模块: 4/4_6.md
    - 4.7 outputs模块: 4/4_7.md
    - 4.8 utils模块: 4/4_8.md
  - 五、VAE技术文档:
    - 5.1 VAE: 5/5_1.md
    - 5.2 FC VAE: 5/5_2.md
  - 六、实验:
    - 6.1 参数修改: 6/6_1.md