site_name: SR NJU
theme:
  name: 'material'
nav:
  - Index: index.md
  - 一、关于mkdocs: 
    - 1.1 mkdocs的使用和书写: 1/1_1.md
  - 二、服务器技术文档:
    - 2.1 服务器基本信息: 2/2_1.md
    - 2.2 服务器环境信息: 2/2_2.md
    - 2.3 服务器使用方法: 2/2_3.md
    - 2.4 服务器操作笔记: 2/gpu_summary.md
  - 三、Python虚拟环境:
    - 3.1 预备知识: 3/3_1.md
    - 3.2 Windows配置虚拟环境: 3/3_2.md
    - 3.3 复现THU-DL-SR记录(outdated): 3/3_3.md
    - 3.4 演示: 3/3_4.md
    - 3.5 python操作笔记: 3/py_summary.md
  - 四、VAE 模型:
    - 4.1 程序结构: 4/4_1.md
    - 4.2 网络结构: 4/4_2.md
    - 4.3 LOSS函数与优化器: 4/4_3.md

